#!/bin/csh

setenv LEV 25.0		# 1-49 works

foreach f (../result/*.nc)
	setenv FIN $f
	set fno = $f:t
	setenv FON $fno:r
	ncl draw.ncl
	convert -trim -density 150 $FON.eps $FON.jpg
	rm -f $FON.eps
	echo "processing ... $FON"
end

rm -rf pic
mkdir pic
mv -f *.jpg pic
